### ISSUE TITLE
Connection closed by the server

### ISSUE THREAD

**Issue by islcom** [joshkunz/ashuffle#7] opened 2017-03-15 06:38 UTC
Hi, I get the following error;
Picking random songs out of a pool of 8954
MPD error: Connection closed by the server

Standard mpd install on jessie 8

Thanks

**Comment by joshkunz** [comment] 2017-03-20 19:04
What version of MPD is it? Also, are you running MPD on any non-standard ports?

**Comment by joshkunz** [comment] 2017-03-20 20:27
I spun up a clean vm (running debian 8) to try and reproduce this bug but I wasn't able to. I'm using the debian-packaged MPD (version 0.19.1) and libmpdclient (version 2.9).

It's very strange to me that you would get a connection error *after* the song-pool is constructed since that step involves a lot of queries to the MPD server. I would be curious to see what the exact ashuffle invocation was. Also, there's a chance that MPD itself crashed. I'm not exactly sure what's going on here, so any additional information would be appreciated, MPD's logs, an strace of ashuffle, etc.

**Comment by islcom** [comment] 2017-03-20 21:37
My apologies, am running wheezy.

ubaudio@debianmusic:~$ uname -a
Linux debianmusic 3.2.0-4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.78-1 x86_64
GNU/Linux
usbaudio@debianmusic:~$ apt-cache policy mpd
mpd:
  Installed: 0.16.7-2+b1
  Candidate: 0.16.7-2+b1
  Version table:
 *** 0.16.7-2+b1 0
        500 http://ftp.monash.edu.au/pub/linux/debian/ wheezy/main amd64
Packages
        100 /var/lib/dpkg/status
usbaudio@debianmusic:~$ apt-cache policy libmpdclient-dev
libmpdclient-dev:
  Installed: 2.3-1
  Candidate: 2.3-1
  Version table:
 *** 2.3-1 0
        500 http://ftp.monash.edu.au/pub/linux/debian/ wheezy/main amd64
Packages
        100 /var/lib/dpkg/status

Will install Jessie, mpd 0.19.1 and libmpdclient 2.9

Thanks

**Comment by joshkunz** [comment] 2017-03-21 06:08
No worries. Since that is a pretty old version of libmpdclient, I'm gonna blame that, and close this issue. If anyone *really* needs to run on versions that old, they can reopen it.

**Closed by joshkunz** 2017-03-21 06:08 UTC
