### ISSUE TITLE
Ashuffle stops when a file is not found

### ISSUE THREAD

**Issue by vesubian** [joshkunz/ashuffle#93] opened 2021-03-12 10:01 UTC
I am experimenting with a web radio so I have a continuous broadcast of a large library playing at random with ashuffle.

Sometimes a file is not found (did not find the reason yet, maybe just need an `mpc update` to run).

In such cases, the playlist is started over and replayed. If I delete the unfound file and play the last track on the playlist, then ashuffle takes over again.

I would expect/like ashuffle to skip through the unfound file and pick another one instead, and in any case to keep on going.

I use ashuffle with a queue buffer of 1.

**Comment by joshkunz** [comment] 2021-03-12 17:20
This appears to be a duplicate of #94. Closing this. I will follow-up in #94 instead.

**Closed by joshkunz** 2021-03-12 17:20 UTC
