### ISSUE TITLE
Support reading from pipe for continuous adding of songs

### ISSUE THREAD

**Issue by bartkl** [joshkunz/ashuffle#140] opened 2022-05-31 07:28 UTC
Hi,

I often find myself adding Ambient tracks for one hour, and then I get in a different mood and would like a different pool altogether. From what I understand, if you want to select different songs, you have to restart `ashuffle`. I would love to be able to feed it new songs while it waits for those and processes those.

I hoped redirecting ashuffle's stdin to a pipe to which I write file URIs would work with `--file -`, but it doesn't. I'm keeping the pipe open so I guess the lack of `EOF` it choking ashuffle. To be more specific, this is how I tried doing it:

```tail -f -n1 ~/queue.pipe | /usr/local/bin/ashuffle --queue-buffer 1 --file -```

Anyways, curious if you have any thoughts or helpful ideas.

Long-time who loves the library, thanks!
Bart

**Comment by joshkunz** [comment] 2022-06-02 04:15
Currently, ashuffle will wait for the full list of songs to build the shuffle list before it starts playing. This is a limitation of the `-f` "protocol" so to speak.[^1] There's no way to signal that you're done sending songs besides closing the file. To support this, we'd have to add some way to signal the "end" of the list of songs so ashuffle can start shuffling.

My main question is: Why do you need to dynamically change ashuffle's song list? Restarting ashuffle shouldn't really be any more noticeable than changing your song list. The previously enqueued song would keep playing and the newly started ashuffle would patiently wait to re-enqueue a song *after* the song enqueued by the previous ashuffle instance finished. I even hacked together a little demo with `socat`:

Assuming you had a file called `run_ashuffle.sh` that looked like:
```bash
#!/bin/bash

# Remove the old instance
pkill ashuffle
cat | ashuffle -f - &
```

And you ran a socat server like:
```bash
socat -u UNIX-LISTEN:<some-path>,fork EXEC:$PWD/run_ashuffle.sh
```

You could dynamically change the list by doing something like:

```bash
cat playlist | socat STDIO UNIX:<some-path>
```

That would automatically kill the old ashuffle instance, and then re-start ashuffle with the new songs in "playlist".

Given that there are work-arounds like this, I'm hesitant to add this `ashuffle` proper unless this work-around has some big issue like its too slow (music pauses) or doesn't work.

[^1]: This is just one of these limitations. ashuffle also supports shuffling via "groups" (see `--group-by`) which can't be independently supplied via `-f`

**Comment by bartkl** [comment] 2022-06-02 12:43
One reason why I might have feared ashuffle restarts is because on my Raspberry Pi the start-up times are definitely (quite) noticeable with larger selections (for example in the order of 10k songs). However, it's probably a brainfart to attribute that to the start-up time, since it's the pooling of large selections that just takes a while to process.

The suggested solution sounds nice, and you're probably right it makes the need for changes to ashuffle unnecessary. I'm quite comfortable with the Linux shell, but wasn't aware of `socat`. I'm going to try it out.

Thanks!

**Comment by bartkl** [comment] 2022-06-03 06:55
It works like a charm! I love this solution. The compositiona strength of Linux keeps amazing me.

I did spend half an hour debugging before finally learning that `pkill ashuffle` also kills `ashuffled`, which is what I named the script you named `run_ashuffle.sh` ;). Adding `--exact` took care of that.

Anyways, works great. Thanks for the solution and teaching me something new in the process.

**Comment by joshkunz** [comment] 2022-06-14 06:01
> However, it's probably a brainfart to attribute that to the start-up time, since it's the pooling of large selections that just takes a while to process.

Yeah, I do have some performance regression tests for startup speed, and it's OK, but not as fast as I'd like. What I'd really like to do is eventually implement some async behavior when ashuffle can start queuing music before the selection is fully loaded and grouped. That's a tricky feature though, and startup speed is OK, so I haven't bothered with it yet.

> It works like a charm!

🎉 

> I did spend half an hour debugging ...

Oops sorry about that! I actually ran into a similar issue when I was testing the proposed fix, but I just renamed the scripts. I should have mentioned it! Thanks for teaching me about the `--exact` flag.

> If you like I could contribute to the wiki here or something, who knows there's more people who'd enjoy this.

I'm going to close out this issue since it seems like this solution is working. If you'd like to contribute instructions, you can open a PR with your change in the `/contrib` folder (https://github.com/joshkunz/ashuffle/tree/master/contrib).

**Closed by joshkunz** 2022-06-14 06:01 UTC
Labels: enhancement
