### ISSUE TITLE
Ashuffle does not stop when oneshot single mode is enabled

### ISSUE THREAD

**Issue by bartkl** [joshkunz/ashuffle#142] opened 2022-06-04 08:38 UTC
[Since MPD 0.21](https://mpd.readthedocs.io/en/stable/protocol.html#since-0-21), a oneshot variation to the single mode has been introduced which is basically the original single mode, but it resets the single status to off afterwards.

```
$ mpc single once
volume: 33%   repeat: off   random: off   single: once  consume: off
```
However, ashuffle does not respect the setting, i.e. ignores it as if single mode was simply off. This is probably due to few people and clients using it, and its relative "newness".

**Comment by joshkunz** [comment] 2022-06-05 19:44
Looks like recent versions of libmpdclient do support the option, so this should be supportable in ashuffle. I'm not really sure what the expected behavior is here though. By my understanding: toggling on `oneshot` single mode basically causes MPD to stop playing once the currently playing song is finished, but also turns off single mode at that point. Is the expectation that ashuffle would also stop enquing songs at that point until songs started playing in MPD again? Or would you expect ashuffle to immediate try enquing songs?

**Comment by bartkl** [comment] 2022-06-07 07:29
My expectation (and wish) would be that ashuffle stops playing, and resets the single mode to off.

**Comment by joshkunz** [comment] 2022-06-12 21:03
> Perhaps keep it consistent with the regular single mode behavior.

Gotcha, that makes sense. The tricky thing is that right now we rely on [querying the single status](https://github.com/joshkunz/ashuffle/blob/00d6ca1594874b9577de0f64c0fc0468e432c744/src/ashuffle.cc#L107-L109) from MPD in order to control single behavior. Since MPD has cleared the single status at that point, we'll need to track the status independently of MPD. Luckily it looks like there is an [`options` IDLE command](https://mpd.readthedocs.io/en/latest/protocol.html#querying-mpd-s-status) so in theory we could track that state.

**Comment by joshkunz** [comment] 2022-06-14 08:06
OK I was looking at the implementation of this, and I ran into a bit of a weird situation on how `single: oneshot` works when you reach the end of the playlist.

This is on MPD 0.23.7. If I turn on single oneshot mode on the last song in the playlist, when the player reaches the end of the queue, single oneshot mode is *not* turned off. That is if I do `mpc listall | head -n1 | mpc add; mpc play $(mpc playlist | wc -l)` (add another song to the queue, and play it), single oneshot mode stays on. You could keep repeating this and single oneshot mode would never be turned off.

`ashuffle` only starts playing songs when a new song is added after the end of the queue, and single mode is not turned on. The thing is that it already (i.e. the latest released version) considers oneshot single mode to be "single mode is turned on" for the purposes of triggering a play. `ashuffle` should never really be triggering erroneous plays in this mode.

Could you provide a specific sequence of events & player state that you wish worked differently so I can figure out what's going on here? If you could also include your libmpdclient version that would be helpful. I assume it's fairly recent since your `mpc` output snippet contains the `single: once` printout, but I just want to make sure I'm looking at the right thing.

**Comment by joshkunz** [comment] 2022-06-19 04:24
Thanks for the details!

I think the version of `libmpdclient` is what's going on here. Support for single "oneshot" mode was added in libmpdclient 2.18, but you're running 2.16. I can actually reproduce the issue you're seeing with libmpdclient 2.16, but if I keep everything else the same, and upgrade libmpdclient to 2.18 the issue goes away, and `ashuffle` works just like normal in this situation.

Since ashuffle relies on `libmpdclient` for communication with MPD, there's not much we can do to make this flow work on older versions of libmpdclient. I recommend upgrading and seeing if that fixes it.

On a side note, I'm kind-of surprised that the `mpc` output snippet you provided in your first message worked. I'd assume that `mpc` was using the same system libmpdclient, but it looks like it's not.

**Comment by bartkl** [comment] 2022-06-21 06:08
Sorry for not mentioning that yes, I indeed ran `mpc` from another system which has a newer version. Good catch!

The only thing I'm confused about is how one shot single mode could work with my outdated MPD backend (which it does). But let's not break our heads over this any further. I'll see if I can upgrade I check if that works. It's a Raspbian (Debian based) system, so I might have to compile from source, but that might be a nice option anyways.

Thanks for the help!

**Comment by joshkunz** [comment] 2022-06-21 06:19
> The only thing I'm confused about is how one shot single mode could work with my outdated MPD backend (which it does).

In your setup (based on your comment above) your MPD release (server) supports oneshot mode, it's just libmpdclient (client) that doesn't. Upgrading the client will add support for oneshot mode.

> so I might have to compile from source, but that might be a nice option anyways.

Sorry about this! Really not much `ashuffle` can do here without dropping the dependency on `libmpdclient`, which would mean re-implementing the MPD protocol layer provided by that library.

**Comment by bartkl** [comment] 2022-06-21 06:22
Ohh now I get it. And since ashuffle runs on the server machine, it has to deal with the old `libmpdclient` version.

No worries, and thanks again.

**Comment by joshkunz** [comment] 2022-06-22 07:07
Closing out since I think the original issues was solved.

**Closed by joshkunz** 2022-06-22 07:07 UTC
